default: &default
  adapter: postgresql
  encoding: unicode
  host: postgres
  username: <%= ENV.fetch("POSTGRES_USER") %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD") %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: financial_control_development

test:
  <<: *default
  database: financial_control_test

production:
  <<: *default
  database: financial_control_production
